language: R
cache: packages
sudo: false

r:
- oldrel
- release
- devel

os:
  - linux

# No OpenMp support on Travis OSX build
#  - osx

r_packages:
  - covr
  - lintr
  - bit64

after_success:
  - Rscript -e 'library(covr); codecov()'
