language: R
cache: packages
sudo: false

r:
- oldrel
- release
- devel

os:
  - linux

# No OpenMp support on Travis OSX build
#  - osx

r_packages:
  - covr

r_github_packages:
  - jimhester/lintr

after_success:
  - Rscript -e 'library(covr); codecov()'
