language: R
cache: packages
sudo: false

r:
- oldrel
- release
- devel

os:
  - linux

r_packages:
  - covr
  - lintr
  - bit64
  - nanotime
  - data.table

after_success:
  - Rscript -e 'library(covr); codecov()'
