language: R
cache: packages
sudo: false

r:
- oldrel
- release
- devel

os:
  - linux
  - osx

r_packages:
  - covr
  - lintr
  - bit64
  - nanotime

after_success:
  - Rscript -e 'library(covr); codecov()'
