language: R
cache: packages
sudo: false
warnings_are_errors: true

matrix:
  include:
  - r: release
  - r: oldrel
  - r: devel
  - os: osx
  - os: linux
allow_failures:
  - os: osx

r_packages:
  - covr
  - lintr
  - bit64
  - nanotime
  - testthat
  - data.table

after_success:
  - Rscript -e 'library(covr); codecov()'

env:
  global:
    - PKG_CFLAGS="-O3 -Wall -pedantic"
