language: R
cache: packages
sudo: false
warnings_are_errors: true

r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

# matrix:
#  exclude:
#  - r: release
#    os: osx
#  - r: devel
#    os: osx
#  - r: devel
#    os: linux

r_packages:
  - covr
  - lintr
  - bit64
  - nanotime
  - testthat
  - data.table

after_success:
  - Rscript -e 'library(covr); codecov()'

env:
  global:
    - PKG_CFLAGS="-O3 -Wall -pedantic"
